### ISSUE TITLE
Instructions are overcomplicated

### ISSUE THREAD

**Issue by InfoTeddy** [perguto/VVVVVV-SiIvagunner-Mod#1]
The instructions in the readme are overcomplicated and unnecessary. There is no need to modify `data.zip` to install this mod. Instead, you can just place the files in the customization directory. The easiest way to do this is to go to "levels", then select "open level folder", and go up one subfolder to `VVVVVV/`. Then `vvvvvvmusic.vvv` can be placed in there, along with `graphics/` (containing `sprites.png`) and `sounds/` (containing `souleyeminijingle.wav`).

**Comment by GraysonMakesGames** [comment]
I agree. They should be rewritten with how you describe it

**Comment by perguto** [comment]
Thanks, I updated the readme accordingly
